# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Shaun Cheung
tagline:             'Discover. Analyse. Execute.'
description:         'Backed by solid understanding of business fundamentals with Accounting and Finance knowledge and strong business acumen through years of sales experience --- Now with newfound data science skills --- I hope to provide insights through customer analytics to improve sales and increase customer satisfaction.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/mlampros
  
analyticsvidhya:       https://www.analyticsvidhya.com/

r_users:          https://www.r-users.com/
