# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Shaun Cheung
tagline:             'Identify. Analyse. Interpret.'
description:         'Backed by solid understanding of business fundamentals with Accounting and Finance knowledge and strong business acumen through years of sales experience --- Now with newfound data science skills --- I hope to provide insights through customer analytics to improve sales and increase customer satisfaction.'
url:                 shauncheungkt.github.io
baseurl:             ''
# Use paginate to set the number of pages shown
paginate:            5

# About/contact
author:
  name:              'Shaun Cheung'
  email:             shauncheungkt@gmail.com

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/shauncheungkt
  
analyticsvidhya:       https://www.analyticsvidhya.com/

